### ISSUE TITLE
deployment issue

### ISSUE THREAD

**Issue by fvthree** [yosriady/serverless-crud-go#1]
Hi bro,

I have this problem and it's quite frustrating. 

Can you assist me to resolve this issue?

![capture](https://user-images.githubusercontent.com/5683379/40269070-56866acc-5bab-11e8-956b-295d793458de.PNG)

Thank you

**Comment by fvthree** [comment]
Here's the serverless.yml file

[serverless.yml.txt](https://github.com/yosriady/serverless-crud-go/files/2019473/serverless.yml.txt)

**Comment by fvthree** [comment]
Oh! I got it already. 
I moved the build.sh and deploy.sh file outside its directory.

So here's my directory structure:

serverless-go
  -src folder
  build.sh
  deploy.sh
  serverless.yml

note that im working on windows 10

**Comment by yosriady** [comment]
Hmm if you run the build and deploy scripts when your current working directory is the project's root directory like `./scripts/build.sh`, does it not work? That way you don't have to move the scripts.

 I've only tested the scripts on OSX.
